[alembic]
script_location = fast_api/db/migrations
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic,fast_api

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_fast_api]
level = INFO
handlers =
qualname = fast_api

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

[post_write_hooks]
hooks = ruff_format, ruff_check
ruff_format.type = exec
ruff_format.executable = %(here)s/.venv/bin/ruff
ruff_format.options = format REVISION_SCRIPT_FILENAME
ruff_check.type = exec
ruff_check.executable = %(here)s/.venv/bin/ruff
ruff_check.options = check --fix REVISION_SCRIPT_FILENAME
